- id: zaqar-keystone
  type: puppet
  groups: [primary-controller]
  version: 2.1.0
  requires: [primary-openstack-controller]
  required_for: [zaqar-db]
  cross-depends:
    - name: keystone-db
    - name: zaqar-db
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/keystone.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: zaqar-db
  type: puppet
  groups: [primary-controller]
  version: 2.1.0
  required_for: []
  requires: []
  condition:
    yaql_exp: >
      changedAny($.mysql, $.network_metadata.vips, $.get('database_vip'))
  cross-depends:
    - name: /^(primary-)?database$/
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/db.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: openstack-haproxy-zaqar
  type: puppet
  version: 2.1.0
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  requires: [primary-cluster-haproxy, cluster-haproxy]
  # condition:
  #   yaql_exp: >
  #     changedAny($.keystone, $.public_ssl, $.get('use_ssl'),
  #     $.get('external_lb'),
  #     $.network_metadata.nodes.values().where(
  #       ('controller' in $.node_roles) or
  #       ('primary-controller' in $.node_roles)),
  #     $.get('keystone_names'), $.get('keystone_ipaddresses'),
  #     $.get('public_service_endpoint'), $.network_metadata.vips)
  cross-depends:
    - name: /(primary-)?cluster-haproxy/
      role: self
  parameters:
    puppet_manifest: 'puppet/manifests/openstack-haproxy-zaqar.pp'
    puppet_modules: 'epuppet/modules:/etc/puppet/modules'
    timeout: 300


- id: primary-zaqar
  type: puppet
  version: 2.1.0
  groups: [primary-controller]
  required_for: [deploy_end]
  requires: [primary-openstack-controller, openstack-controller]
  # condition:
  #   yaql_exp: &heat_enabled >
  #     changedAny($.network_scheme, $.heat, $.sahara, $.rabbit, $.ceilometer,
  #     $.get('max_retries'), $.get('max_pool_size'), $.get('max_overflow'),
  #     $.get('idle_timeout'), $.network_metadata.vips, $.public_ssl,
  #     $.get('use_ssl'), ('primary-controller' in $.roles),
  #     $.get('kombu_compression'), $.get('heat_endpoint'), $.debug,
  #     $.get('verbose'), $.get('use_stderr'), $.get('use_syslog'),
  #     $.get('syslog_log_facility_heat'), $.deployment_mode,
  #     $.get('region', 'RegionOne'), $.get('external_lb'),
  #     $.get('database_vip'), $.get('heat_db_name'), $.storage,
  #     $.network_metadata.nodes.values().where(
  #       $.node_roles.any($.matches('controller'))).network_roles.select(
  #         $.get('mgmt/messaging')), $.get('amqp_hosts'),
  #     $.configuration.get('heat'), $.configuration.get('heat_api_paste_ini'),
  #     $.get('heat_ha_engine'))
  cross-depends:
    - name: zaqar-db
    - name: zaqar-keystone
    - name: memcached
  parameters:
    puppet_manifest: 'puppet/manifests/zaqar-controller.pp'
    puppet_modules: 'puppet/modules:/etc/puppet/modules'
    timeout: 300

- id: zaqar
  type: puppet
  version: 2.1.0
  groups: [controller]
  required_for: [deploy_end]
  requires: [primary-openstack-controller, openstack-controller]
  # condition:
  #   yaql_exp: *heat_enabled
  cross-depends:
    - name: primary-zaqar
  parameters:
    puppet_manifest: 'puppet/manifests/zaqar-controller.pp'
    puppet_modules: 'puppet/modules:/etc/puppet/modules'
    timeout: 300

# NOTE(pchechetin) --- READY DELIMETER

#- id: fuel-plugin-zaqar-post-deployment-sh
#  type: shell
#  role: [fuel-plugin-zaqar_role]
#  version: 2.0.0
#  cross-depends:
#    - name: post_deployment_start
#  cross-depended-by:
#    - name: post_deployment_end
# #  requires: [post_deployment_start]
# #  required_for: [post_deployment_end]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: fuel-plugin-zaqar-pre-deployment-sh
#  type: shell
#  role: [fuel-plugin-zaqar_role]
#  version: 2.0.0
#  cross-depends:
#    - name: pre_deployment_start
#  cross-depended-by:
#    - name: pre_deployment_end
# #  requires: [pre_deployment_start]
# #  required_for: [pre_deployment_end]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
