attributes:
  metadata:
    group: 'openstack_services'
  # fuel-plugin-zaqar_text:
  #   value: 'Set default value'
  #   label: 'Text field'
  #   description: 'Description for text field'
  #   weight: 25
  #   type: "text"
